apiVersion: apps/v1
kind: Deployment
metadata:
  name: college-bus-backend
  namespace: college-bus
  labels:
    app: college-bus-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: college-bus-backend
  template:
    metadata:
      labels:
        app: college-bus-backend
    spec:
      containers:
        - name: backend
          image: sarath1236/college-bus-backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SUPABASE_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SUPABASE_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20