apiVersion: v1
kind: Service
metadata:
  name: college-bus-backend-service
  namespace: college-bus
spec:
  type: NodePort
  selector:
    app: college-bus-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500