apiVersion: apps/v1
kind: Deployment
metadata:
  name: college-bus-frontend
  namespace: college-bus
  labels:
    app: college-bus-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: college-bus-frontend
  template:
    metadata:
      labels:
        app: college-bus-frontend
    spec:
      containers:
        - name: frontend
          image: sarath1236/college-bus-frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80